
language: rust
rust:
  - 1.20.0

install:
- curl -OL https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
- unzip protoc-3.4.0-linux-x86_64.zip -d protoc3
- sudo mv protoc3/bin/* /usr/local/bin && sudo chmod 775 /usr/local/bin/*
- sudo mv protoc3/include/* /usr/local/include && sudo chmod -R 755 /usr/local/include

script:
- make vendor
- ls -lah vendor
# - make release


# deploy:
#   provider: releases
#   skip_cleanup: true
#   file_glob: true
#   file: diplomat.tar.gz
#   api_key:
#     secure: xxxxxxxxx
#   on:
#     tags: true
#     repo: timperrett/diplomat
