[package]
name = "consort"
version = "0.1.0"
authors = ["Timothy Perrett <timothy@getintheloop.eu>"]

[dependencies]
grpc            = "0.*"
protobuf        = "1.*"
futures         = "0.1"
futures-cpupool = "0.1"
