[package]
name = "diplomat"
version = "0.1.0"
authors = [ "Timothy Perrett" ]

[dependencies]
grpcio          = "0.1"
protobuf        = "1.4.1"
futures         = "0.1"
futures-cpupool = "0.1"
consul          = "0.2"
clap            = "2.24"
prometheus      = "0.2"
